// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njrjdtnrbqpzdjisheic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qcmpkdG5yYnFwemRqaXNoZWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjU2MDAsImV4cCI6MjA2NjM0MTYwMH0.Io3OUACnuonJrDgmeU6Z9gxDsRWrtvrUQRUEbERjOWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);